spring:
  application:
    name: users
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: mardok1825@gmail.com
    password: gybmmfyodcprfedo
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true