spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties.mail.smtp:
      auth: true
      starttls.enable: true


