server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
eureka:
  instance:
    preferIpAddress: true
    hostname: discovery-0
  client:
    service-url:
      defaultZone: http://discovery-0.discovery.default.svc.cluster.local:8761/eureka