apiVersion: v1
data:
  security_user: YWRtaW4=
  security_password: YWRtaW4=
kind: Secret
metadata:
  name: gateway-secrets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: skandharoots/apigateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8222
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: loki-cfg
            - name: SECURITY_USER
              valueFrom:
                secretKeyRef:
                  key: security_user
                  name: gateway-secrets
            - name: SECURITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: security_password
                  name: gateway-secrets
      initContainers:
          # Wait for discovery to show up
        - name: wait-for-discovery
          image: busybox
          command: [ "sh", "-c", "until nc -zv discovery-0.discovery.default.svc.cluster.local 8761 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]
          #Wait for config server to show up
        - name: wait-for-config-server
          image: busybox
          command: [ "sh", "-c", "until nc -zv config-server-svc.default.svc.cluster.local 80 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]
---

kind: Service
apiVersion: v1
metadata:
  name: apigateway-svc
spec:
  selector:
    app: apigateway
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8222
      protocol: TCP

