apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-service
  labels:
    app: azure-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-service
  template:
    metadata:
      labels:
        app: azure-service
    spec:
      containers:
        - name: azure-service
          image: skandharoots/azure-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8020
          readinessProbe:
            tcpSocket:
              port: 8020
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8020
              path: /actuator/health
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm
            - name: SPRING_CLOUD_AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  key: azr_con_str
                  name: azurite-cfg
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: loki-cfg
      initContainers:
          # Wait for discovery to show up
        - name: wait-for-discovery
          image: busybox
          command: [ "sh", "-c", "until nc -zv discovery-0.discovery.default.svc.cluster.local 8761 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]
          #Wait for config server to show up
        - name: wait-for-config-server
          image: busybox
          command: [ "sh", "-c", "until nc -zv config-server-svc.default.svc.cluster.local 80 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]

---

kind: Service
apiVersion: v1
metadata:
  name: azure-service-svc
spec:
  selector:
    app: azure-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 0
      protocol: TCP

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: azurite-cfg
data:
  azr_con_str: "DefaultEndpointsProtocol=https;AccountName=musicstoreproductsblob;AccountKey=8DQIKrOuI0EEBUzT2SR7m2JZBDbZvuYY7hqx/zVR7FCi66ApBA7CpuqRPM4aMciJAvXYralj3pPA+ASt2d7gfQ==;EndpointSuffix=core.windows.net"



