apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-service
  labels:
    app: azure-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-service
  template:
    metadata:
      labels:
        app: azure-service
    spec:
      containers:
        - name: azure-service
          image: skandharoots/azure-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm

---

kind: Service
apiVersion: v1
metadata:
  name: azure-service-svc
spec:
  selector:
    app: azure-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 0
      protocol: TCP

