apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          imagePullPolicy: Always
          image: skandharoots/config-server:latest
          ports:
            - containerPort: 8889
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: config_hostname
                  name: discovery-config-cm
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  key: config_discovery_server_address
                  name: discovery-config-cm
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  key: config_discovery_server_uri_for_gateway
                  name: discovery-config-cm
      initContainers:
          # Wait for discovery to show up
        - name: wait-for-discovery
          image: busybox
          command: [ "sh", "-c", "until nc -zv discovery-0.discovery.default.svc.cluster.local 8761 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]

---

apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8889
  selector:
    app: config-server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-cm
data:
  config-server-url: "optional:configserver:http://config-server-svc.default.svc.cluster.local:80"

