apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-cm
data:
  discovery_server_address: "http://discovery-0.discovery:8761/eureka,http://discovery-1.discovery:8761/eureka"
  hostname: "${HOSTNAME}.discovery"

---

apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: discovery
      protocol: TCP
  selector:
    app: discovery

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery
spec:
  selector:
    matchLabels:
      app: discovery
  serviceName: discovery
  replicas: 2
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          imagePullPolicy: Always
          image: skandharoots/discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  key: discovery_server_address
                  name: discovery-cm
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: hostname
                  name: discovery-cm
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-lb
  labels:
    app: discovery
spec:
  selector:
    app: discovery
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-config-cm
data:
  config_discovery_server_address: "http://discovery-0.discovery.default.svc.cluster.local:8761/eureka"
  config_hostname: "discovery-0"
  config_discovery_server_uri_for_gateway: "http://discovery-0.discovery.default.svc.cluster.local:8761,http://discovery-1.discovery.default.svc.cluster.local:8761"

