apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: skandharoots/order:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm

---

kind: Service
apiVersion: v1
metadata:
  name: order-svc
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 0
      protocol: TCP

