apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: skandharoots/order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8030
          readinessProbe:
            tcpSocket:
              port: 8030
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8030
              path: /actuator/health
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: mysql_orders_url
                  name: mysql-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mysql_username
                  name: mysql-secrets
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_root_password
                  name: mysql-secrets
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: loki-cfg
      initContainers:
        #Wait for mysql to show up
        - name: wait-for-mysql
          image: busybox
          command: [ "sh", "-c", "until nc -zv mysql.default.svc.cluster.local 3306 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]
          # Wait for discovery to show up
        - name: wait-for-discovery
          image: busybox
          command: [ "sh", "-c", "until nc -zv discovery-0.discovery.default.svc.cluster.local 8761 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]
          #Wait for config server to show up
        - name: wait-for-config-server
          image: busybox
          command: [ "sh", "-c", "until nc -zv config-server-svc.default.svc.cluster.local 80 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]

---

kind: Service
apiVersion: v1
metadata:
  name: order-svc
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8030
      protocol: TCP

