apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: skandharoots/products:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm

---

kind: Service
apiVersion: v1
metadata:
  name: products-svc
spec:
  selector:
    app: products
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 0
      protocol: TCP

