apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
  labels:
    app: shopping-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: skandharoots/shopping-cart:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm

---

kind: Service
apiVersion: v1
metadata:
  name: shopping-cart-svc
spec:
  selector:
    app: shopping-cart
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 0
      protocol: TCP

