apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: skandharoots/users:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: config-server-url
                  name: config-server-cm
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: pg_url
                  name: postgres-config
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: postgres-secret-cred
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postgres_username
                  name: postgres-secret-cred
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: loki-cfg
      initContainers:
          #Wait for postgres to show up
        - name: wait-for-postgres
          image: busybox
          command: [ "sh", "-c", "until nc -zv postgres.default.svc.cluster.local 5432 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]
          # Wait for discovery to show up
        - name: wait-for-discovery
          image: busybox
          command: [ "sh", "-c", "until nc -zv discovery-0.discovery.default.svc.cluster.local 8761 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]
          #Wait for config server to show up
        - name: wait-for-config-server
          image: busybox
          command: [ "sh", "-c", "until nc -zv config-server-svc.default.svc.cluster.local 80 > /dev/null; do echo Waiting for master.; sleep 2; done;" ]

---

kind: Service
apiVersion: v1
metadata:
  name: users-svc
spec:
  selector:
    app: users
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8060
      protocol: TCP

