apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: skandharoots/users:latest
          imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: users-svc
spec:
  selector:
    app: users
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 0
      protocol: TCP

