spring:
  application:
    name: azure-service
  config:
    import: optional:configserver:http://localhost:8889
  cloud:
    azure:
      storage:
        blob:
          container-name: products
        connection:
          string: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
my:
  admin_authorize_url: http://USERS/api/users/adminauthorize?token=
server:
  tomcat:
    keep-alive-timeout: 5000
    connection-timeout: 5000
    max-swallow-size: 40MB
    max-http-form-post-size: 40MB
    background-processor-delay: 5000
