spring:
  application:
    name: azure-service
  config:
    import: optional:configserver:http://localhost:8889
  cloud:
    azure:
      storage:
        blob:
          container-name: products
        connection:
          string: DefaultEndpointsProtocol=https;AccountName=musicstoreproductsblob;AccountKey=8DQIKrOuI0EEBUzT2SR7m2JZBDbZvuYY7hqx/zVR7FCi66ApBA7CpuqRPM4aMciJAvXYralj3pPA+ASt2d7gfQ==;EndpointSuffix=core.windows.net
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 40MB
my:
  admin_authorize_url: http://USERS/api/users/adminauthorize?token=
