spring:
  application:
    name: products
  config:
    import: optional:configserver:http://localhost:8888
server:
  error:
    include-message: always
my:
  admin_url: http://USERS/api/v1/users/adminauthorize?token=