server:
  port: 8222
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        security: INFO
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4000"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/users/** , /users-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/** , /products-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: azure
          uri: lb://azure-service
          predicates:
            - Path=/api/azure/** , /azure-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: shopping-cart
          uri: lb://shopping-cart
          predicates:
            - Path=/api/cart/** , /cart-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/api/order/** , /order-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: azure-invoice
          uri: lb://azure-invoice
          predicates:
            - Path=/api/invoice/** , /invoice-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: opinions
          uri: lb://opinions
          predicates:
            - Path=/api/opinions/** , /opinions-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: favorites
          uri: lb://favorites
          predicates:
            - Path=/api/favorites/** , /favorites-svc/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:4000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: discovery
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /azure-svc/v3/api-docs
        name: Azure Service
      - url: /invoice-svc/v3/api-docs
        name: Azure Invoice Service
      - url: /order-svc/v3/api-docs
        name: Order Service
      - url: /products-svc/v3/api-docs
        name: Product Service
      - url: /cart-svc/v3/api-docs
        name: Shopping Cart Service
      - url: /users-svc/v3/api-docs
        name: User Service
      - url: /opinions-svc/v3/api-docs
        name: Opinions Service
      - url: /favorites-svc/v3/api-docs
        name: Favorites Service
management:
  endpoints:
    web:
      exposure:
        include: "*"









