server:
  port: 8222
  error:
    include-message: always
eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: azure
          uri: lb://azure-service
          predicates:
            - Path=/api/azure/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: shopping-cart
          uri: lb://shopping-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/api/order/**
          filters:
            - JwtAuthFilter
          metadata:
            cors:
              allowedOrigins: "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 30
        - id: discovery
          uri: http://localhost:8761
          predicates:
              - Path=/eureka/web
          filters:
              - SetPath=/
        - id: discovery-static
          uri: http://localhost:8761
          predicates:
              - Path=/eureka/**