spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    prefer-ip-address: true
    hostname: discovery-0
  client:
    service-url:
      defaultZone: http://discovery-0.discovery.default.svc.cluster.local:8761/eureka
server:
  port: 0
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /order-svc/v3/api-docs
  swagger-ui:
    enabled: true
    path: /order-svc/swagger-ui.html