spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: lapunia2121
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
    com.musicstore.products.service: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /products-svc/v3/api-docs
  swagger-ui:
    enabled: true
    path: /products-svc/swagger-ui.html