spring:
  datasource:
    url: jdbc:mysql://mysql.default.svc.cluster.local:3306/shoppingcarts
    username: root
    password: lapunia2121
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    preferIpAddress: true
    hostname: discovery-0
  client:
    service-url:
      defaultZone: http://discovery-0.discovery.default.svc.cluster.local:8761/eureka
server:
  port: 0
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        security: DEBUG