spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-address: true
    hostname: discovery-0
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8080"
  client:
    service-url:
      defaultZone: http://discovery-0.discovery.default.svc.cluster.local:8761/eureka,http://discovery-1.discovery.default.svc.cluster.local:8761/eureka
server:
  port: 0
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        security: INFO
    com.musicstore.users.service: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /users-svc/v3/api-docs
  swagger-ui:
    enabled: true
    path: /users-svc/swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  observations:
    key-values:
      application: users
  tracing:
    sampling:
      probability: 1.0
