spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lapunia2121
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /users-svc/v3/api-docs
  swagger-ui:
    enabled: true
    path: /users-svc/swagger-ui.html