spring:
  application:
    name: orders
  config:
    import: optional:configserver:http://localhost:8888
my:
  admin_url: http://USERS/api/users/adminauthorize?token=
  order_check_url: http://PRODUCTS/api/products/items/verify_availability
  order_cancellation_url: http://PRODUCTS/api/products/items/cancel_order