apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_DOMAIN
              value: fancystrings.xyz
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "false"
            - name: GF_SERVER_ROOT_URL
              value: https://fancystrings.xyz/grafana
            - name: GF_AUTH_ANONYMOUS_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: GF_AUTH_ANONYMOUS_ENABLED
                  name: grafana-configmap
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              valueFrom:
                configMapKeyRef:
                  key: GF_AUTH_DISABLE_LOGIN_FORM
                  name: grafana-configmap
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_USER
                  name: grafana-configmap
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_PASSWORD
                  name: grafana-configmap
            - name: GF_USERS_ALLOW_SIGNUP
              valueFrom:
                configMapKeyRef:
                  key: GF_USERS_ALLOW_SIGNUP
                  name: grafana-configmap
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---



apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
data:
  GF_AUTH_ANONYMOUS_ENABLED: "false"
  GF_AUTH_DISABLE_LOGIN_FORM: "false"
  GF_USERS_ALLOW_SIGNUP: "false"
  GF_SECURITY_ADMIN_USER: "skandharoots"
  GF_SECURITY_ADMIN_PASSWORD: "i4mf33liN9s4f3"
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.default.svc.cluster.local:9090
        editable: false
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        orgId: 1
        url: http://loki.default.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1