apiVersion: v1
data:
  mysql_root_password: aTRtZjMzbGlOOXM0ZjM=
  mysql_username: c2thbmRoYXJvb3Rz
kind: Secret
metadata:
  name: mysql-secrets

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql_cart_url: "jdbc:mysql://musicstoremysql.mysql.database.azure.com/shoppingcarts"
  mysql_products_url: "jdbc:mysql://musicstoremysql.mysql.database.azure.com/products"
  mysql_orders_url: "jdbc:mysql://musicstoremysql.mysql.database.azure.com/orders"