apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-cred
data:
  postgres_username: c2thbmRoYXJvb3Rz
  postgres_password: aTRtZjMzbGlOOXM0ZjM=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  pg_url: "jdbc:postgresql://musicstorepostgresql.postgres.database.azure.com/postgres"

