apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: skandharoots/config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
---

kind: Service
apiVersion: v1
metadata:
  name: config-server-svc
spec:
  selector:
    app: config-server
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP

