apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-cm
data:
  discovery_server_address: "http://discovery-0.discovery:8761/eureka"

---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: discovery
      protocol: TCP
  selector:
    app: eureka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery
spec:
  selector:
    matchLabels:
      app: discovery
  serviceName: discovery
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          imagePullPolicy: Always
          image: skandharoots/discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: DISCOVERY_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: discovery_server_address
                  name: discovery-cm

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-lb
  labels:
    app: discovery
spec:
  selector:
    app: discovery
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
