spring:
  application:
    name: products
  config:
    import: optional:configserver:http://service/config-server-svc.default.svc.cluster.local:8888
my:
  admin_url: http://USERS/api/users/adminauthorize?token=