spring:
  application:
    name: products
  config:
    import: optional:configserver:http://config-server-0.config-server.default.svc.cluster.local:8888
my:
  admin_url: http://USERS/api/users/adminauthorize?token=