server:
  port: 8222
  error:
    include-message: always
eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthFilter
        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/**
          filters:
            - JwtAuthFilter
        - id: azure
          uri: lb://azure-service
          predicates:
            - Path=/api/azure/**
          filters:
            - JwtAuthFilter
        - id: shopping-cart
          uri: lb://shopping-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - JwtAuthFilter
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/api/order/**
        - id: discovery
          uri: http://localhost:8761
          predicates:
              - Path=/eureka/web
          filters:
              - SetPath=/
        - id: discovery-static
          uri: http://localhost:8761
          predicates:
              - Path=/eureka/**