server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthFilter
        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/**
          filters:
            - JwtAuthFilter
        - id: azure
          uri: lb://azure-service
          predicates:
            - Path=/api/azure/**
          filters:
            - JwtAuthFilter
