spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: lapunia2121
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
logging:
  level:
    org:
      springframework:
        security: DEBUG