spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lapunia2121
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: mardok1825@gmail.com
    password: gybmmfyodcprfedo
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
logging:
  level:
    org:
      springframework:
        security: DEBUG
