spring:
  config:
    import: optional:configserver:http://service/config-server-svc.default.svc.cluster.local:8888
  application:
    name: discovery
eureka:
  username: ${EUREKA_USERNAME:admin}
  password: ${EUREKA_PASSWORD:lapunia@121}