spring:
  application:
    name: discovery
eureka:
  username: ${EUREKA_USERNAME:admin}
  password: ${EUREKA_PASSWORD:lapunia@121}
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8080"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.85
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"
